---
title: Getting and Cleaning Data Project
output: html_document
---

*Stanley Ing*

*Repo for Getting and Cleaning Data Project*

#Overview

The purpose of this project was to demonstrate the ability to collect, work with, and clean a data set, resulting in a data set that is *tidy* and which can be used for subsequent analysis. 

The full description of the data used for this project can be found at [The UCI Machine Learning Repository](http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones)

Furthermore, the source data for this project can be found [here](https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip)

#Project Objectives

Below you will find the project objectives and instruments.

1. Merges the training and the test sets to create one data set.
2. Extracts only the measurements on the mean and standard deviation for each measurement. 
3. Uses descriptive activity names to name the activities in the data set.
4. Appropriately labels the data set with descriptive activity names.
5. Creates a second, independent tidy data set with the average of each variable for each activity and each subject.

#Additional Information

You can find additional information about the variables, data and transformations in the CodeBook.MD file.

